### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fitodic** [littleweaver/django-daguerre#104]
Could you please create a new release that would incorporate the latest changes?

Changes:
* rounding of the newly calculated dimensions
* hash directory path

**Comment by fitodic** [comment]
@melinath Just a friendly reminder... :slightly_smiling_face: A new release would be greatly appreciated.

**Comment by melinath** [comment]
@fitodic thanks for the pokes. On it!

**Comment by raq929** [comment]
All set: https://github.com/littleweaver/django-daguerre/releases/tag/2.2.3

**Comment by fitodic** [comment]
@raq929 @melinath Thank you very much! :slightly_smiling_face:
