### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by robslotboom** [littleweaver/django-daguerre#91]
Reguirements is listing
install_requires=[
        'Pillow<=2.7.0',
        'django>=1.7,<1.9',
        'six>=1.10.0',
    ],

While in docs is written Django & 1.9

**Comment by melinath** [comment]
The docs are correct. You should still be able to install Django 1.9, but yeah, we should bring this in line as well.

**Comment by robslotboom** [comment]
pip install django-daguerre --upgrade --no-cache still has the old reqs.
Isn’t it in synch?

Best regards,

Robert

**Comment by melinath** [comment]
We're working on a point release that will fix this and a couple other small issues. In the meantime, you can simply install Daguerre with `pip install --no-deps django-daguerre` and then manually install pillow and Django (if they aren't already installed.)

**Comment by melinath** [comment]
Clarification, because I can't edit comments from my phone: the fix for this (which has already been included in master) will be included in a point release which will come out at some point this week.
